import * as fs from 'fs';

import * as tf from '@tensorflow/tfjs-node';
import { Tensor3D } from '@tensorflow/tfjs-node';

tf.tidy(() => {
  const bigMess: Tensor3D = tf.randomUniform([400, 400, 3], 0, 255);
  tf.node
    .encodeJpeg(
      bigMess,
      'rgb',
      90,
      true,
      true,
      true,
      'cm',
      250,
      250,
      'Generated by TFJS Node!'
    )
    .then((f) => {
      fs.writeFileSync('img/advance.jpg', f);
      console.log('Finish!');
    });
});
